### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by garside** [Learnosity/learnosity-sdk-python#1]
I haven't tested this, but I am looking over the code, and can't imagine why this line would work:

https://github.com/Learnosity/learnosity-sdk-python/blob/master/learnosity_sdk/request.py#L73

I'm pretty sure it should be:

``` python
  output.update(json.loads(self.request_string))
```

as it has on [line 66](https://github.com/Learnosity/learnosity-sdk-python/blob/master/learnosity_sdk/request.py#L66).

I'm converting this over into a rails sdk and just spotted this issue. Tried in python console and the following causes an error:

``` python
{}.update('string')
```

**Comment by shtrom** [comment]
A bit late dealing with this issue. Sorry about that. The good news is that it looks like this has been fixed in 08952cb7be15678ae2768623307670daeb9d85d, so I'll close this issue.

On another note, we have a native Ruby SDK, now https://github.com/Learnosity/learnosity-sdk-ruby
