### ISSUE TITLE
No module named 'learnosity_sdk.uuid'

### ISSUE THREAD

**Issue by rls-vault** [Learnosity/learnosity-sdk-python#13]
Hello getting an error

> from learnosity_sdk.uuid import Uuid
> ModuleNotFoundError: No module named 'learnosity_sdk.uuid'

From sample in https://github.com/Learnosity/learnosity-sdk-python#usage
I am not sure if this is an old option that has been deprecated, or an error in the sample code

Please look into it as soon as you can
Cheer

**Comment by rls-vault** [comment]
Feedback:
this seems to solve it
from learnosity_sdk.utils import Uuid
#from learnosity_sdk.uuid import Uuid

**Comment by shtrom** [comment]
Fixed in e09e85f91f76f0819ef82110f7c56b2561537751
