### ISSUE TITLE
Authoring Examples missing from reference.

### ISSUE THREAD

**Issue by LagunaElectric** [Learnosity/learnosity-sdk-python#60]
It would be really neat if you'd include some examples of authoring questions/activities with this SDK. Especially if you could document all of the possible fields the data_request can have when doing so!

**Comment by TheRealEdDawson** [comment]
Hi there @LagunaElectric! Thanks for the feedback, we are definitely planning to add some Python SDK examples for authoring Learnosity questions and activities. 

In terms of what options you can put into a request, we have a comprehensive listing over on our reference site, for example, here are all the possible fields (init options) that can be used with Author API: https://reference.learnosity.com/author-api/initialization , and here's the same thing for Items API: https://reference.learnosity.com/items-api/initialization. 

Is that what you were looking for, in terms of the possible fields for the data request? 

Kind Regards, Edwin

**Comment by LagunaElectric** [comment]
I'll have a look and let you know! Thank you so much for a fleshed out response! I appreciate that, sir.
