### ISSUE TITLE
Type stubs

### ISSUE THREAD

**Issue by vmckinney-cainc** [Learnosity/learnosity-sdk-python#74]
Hey Learnosity team,

I was wondering if there are any plans to publish type stubs for this repository.  I work in a Python environment with strict type-checking using a third party type-checker ([pyright](https://github.com/microsoft/pyright)).  It's a pretty small repository so I'd be happy to PR some type stubs (in the form of `.pyi` files adjacent to the existing `.py` files) so that others using type-checkers can access this repository as well.

Best,
Violet

**Comment by slahav** [comment]
bump
